name: fv # You can also change this to another name to avoid warning with existing group.
services:
  backend:
    container_name: fv-backend
    build: .
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    networks:
      - fv-net
    environment:
      - BACKEND_PORT=${BACKEND_PORT}
      - DEBUG=${DEBUG}
networks:
  fv-net: # Check by using `docker network ls` command
    external: true
